language: go

go:
  - 1.7
script:
  - go test -covermode=atomic -coverpkg $(go list ./... | grep -v vendor | xargs | sed 's/ /,/g') $(go list ./... | grep -v vendor)

before_install:
  - go get -u github.com/kardianos/govendor
  - govendor sync

after_success:
- bash <(curl -s https://codecov.io/bash)
